# Generated by Django 5.2.3 on 2025-07-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dareexchange',
            name='ph_no',
            field=models.CharField(default=1234567890, max_length=10),
            preserve_default=False,
        ),
    ]
