# Generated by Django 5.2.3 on 2025-07-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_dareexchange_ph_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dareexchange',
            old_name='dare',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='dareexchange',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='dareexchange',
            name='email',
        ),
        migrations.RemoveField(
            model_name='dareexchange',
            name='ph_no',
        ),
        migrations.AddField(
            model_name='dareexchange',
            name='category',
            field=models.CharField(choices=[('fun', 'Fun'), ('adventure', 'Adventure'), ('social', 'Social'), ('skill', 'Skill')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dareexchange',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
